version: "3.8"

services:
  api-tb40:
    build: .
    container_name: api-tb40
    ports:
      - "4040:4040"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
